config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :games, only: [:show] do
        member do
          post :prepare
          post :confirm
          post :evaluate
          get :historic
        end
      end
    end
  end

  namespace :backend do
    resources :games
    resources :game_turns
    resources :participants
    resources :scenarios
    resources :scenario_broadcasts
    resources :scenario_curves
    resources :scenario_issues
    resources :users
    resources :catalog_items
    root to: 'scenarios#index'
  end

  resources :games do
    collection do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
    end
    member do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
      get :current_turn_broadcasts_and_curves
      get :turns
      post :prepare
      post :start
      post :cancel
      post :pause
      post :resume
      post :stop
      post :trigger_issue
      post :pay_expenses
      post :evaluate
    end
  end
  resources :participants
  resources :participants do
    member do
      get :affairs_with, to: 'participants#affairs_with', path: 'affairs_with/:other_id'
    end
  end
  resources :farms
  resources :actors
  resources :loans
  resources :participations
  resources :contracts do
    member do
      get :execute
      post :execute
      post :cancel
    end
  end
  resources :deal_items, only: [:destroy], path: 'deal-items'
  resources :deals, except: [:index] do
    collection do
      post :add_to_cart
    end
    member do
      post :cancel
      post :checkout
      patch :change_quantity, path: 'change-quantity'
      patch :change_unit_pretax_amount, path: 'change-unit-pretax-amount'
    end
  end
  resources :users
  resources :insurances

  root to: 'games#index'
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to :json
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < BaseController
  include RestfullyManageable
  before_action :authenticate_user!
  before_action :authorize_user!
  layout 'backend'

  protected

  def authorize_user!
    unless current_user.administrator?
      redirect_to root_url, alert: :access_denied.tl
      return false
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  attr_reader :current_participation, :current_participant, :current_game, :current_turn
  helper_method :current_participation, :current_participant, :current_game, :current_turn

  before_action :authenticate_user!
  before_action :set_participation

  layout 'game'

  protected

  # Set env
  def set_participation
    if (@current_participation = Participation.includes(:participant, :game).find_by(id: session[:current_participation_id], user_id: current_user.id))
      @current_participant = @current_participation.participant
      @current_game = @current_participation.game
      @current_turn = @current_game.current_turn.number if @current_game.current_turn
    end
  end

  # Check that game is accessible by user
  def check_game
    return true if current_user.administrator?
    if current_participation
      return check_running_game unless current_participation.organizer?
    end
    false
  end

  # Check that game is running
  def check_running_game
    return true if current_game && current_game.running? && current_game.current_turn
    redirect_to games_url
    false
  end
end

app/views/base/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      = link_to('Game of Farms', root_url, class: 'navbar-brand')
    .collapse.navbar-collapse
      - if current_user
        - if current_user.administrator?
          %ul.nav.navbar-nav
            - [:scenarios, :games, :users].each do |name|
              %li{class: controller_name =~ /^#{name.to_s.singularize}/ ? :active : nil}= link_to("actions.backend/#{name}.index".t, controller: "backend/#{name}".to_sym, action: :index)
        - else
          %ul.nav.navbar-nav

        %ul.nav.navbar-nav.navbar-right
          - if current_participation
            - if current_participant
              - if current_participant.application_url
                %li
                  = link_to(current_participant.application_url) do
                    %i.glyphicon.glyphicon-transfer
              %li
                = link_to(participant_path(current_participant)) do
                  %i.glyphicon.glyphicon-home
            - if @current_game.running?
              - if @game && controller_path == "games" && action_name == "show"
                %li
                  %span.navbar-text= @game.name
              - else
                %li
                  = link_to(game_path(current_participation.game)) do
                    %i.glyphicon.glyphicon-th
              - if (turn = current_game.current_turn)
                %li
                  %p.navbar-text{title: turn.stopped_at.l}
                    %span.glyphicon.glyphicon-hourglass
                    %span#main-countdown{data: {countdown: turn.stopped_at.utc.l(format: '%Y-%m-%dT%H:%M:%S'), countdown_restart: current_turn_games_path}}
                %li
                  %p.navbar-text
                    %span.glyphicon.glyphicon-calendar
                    %span#turn-name.date= turn.name

          - if current_user
            %li.dropdown
              = link_to('#', class: 'dropdown-toggle', data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: 'true', expanded: 'false'}) do
                %i.glyphicon{class: "glyphicon-#{!current_participation ? :user : current_participation.organizer? ? :king : current_participation.participant.farm? ? :grain : :briefcase}"}
                - if current_participant
                  = current_participant.name
                %span.caret
              %ul.dropdown-menu
                - if current_game && current_game.running?
                  %li.dropdown-header= "Affichage"
                  - modes = [:simple, :map, :curves]
                  - modes << :rating if current_participation.organizer? || current_user.administrator?
                  - modes.each do |mode|
                    %li{class: (mode.to_s == session[:view_mode].to_s ? 'active' : nil)}= link_to("#{mode}_view_mode".tl, {mode: mode})
                  %li.divider{role: 'separator'}
                - current_user.active_games.each do |game|
                  - if game.current_turn.nil?
                    - Time.now > game.last_turn.stopped_at ? turn_info = 'Partie terminée' :  turn_info = 'La partie est en pause'
                  - else
                    - turn_info = "#{game.current_turn.number}/#{game.turns_count}"
                  %li.dropdown-header= "#{game.name} (#{turn_info})"
                  - game.participations.where(user_id: current_user.id).sort{|a,b| a.name <=> b.name }.each do |participation|
                    - classes = []
                    - classes << :active if current_participation == participation
                    %li{class: classes}
                      = link_to(participation_path(participation)) do
                        %span.glyphicon{class: "glyphicon-#{participation.organizer? ? :king : participation.participant.farm? ? :grain : :briefcase}"}
                        = participation.name
                  %li.divider{role: 'separator'}
                %li= link_to('Mon compte', user_path(current_user))
                %li= link_to('Se déconnecter', destroy_user_session_path, method: :delete)

app/views/base/_tabbox.html.haml
.tabbox
  %ul.nav.nav-tabs{role: "tablist"}
    - tabber.tabs.each do |tab|
      %li{role: "presentation", class: (tab.active ? 'active' : nil)}
        = link_to(tab.label, "##{tab.id}", aria: {controls: tab.id}, role: "tab", data: {toggle: "tab"})
  .tab-content
    - tabber.tabs.each do |tab|
      .tab-pane{role: "tabpanel", class: (tab.active ? 'active' : nil), id: tab.id}= tab.content

app/views/base/create.html.haml
new.html.haml

app/views/base/edit.html.haml
= simple_form_for [resource], class: 'form' do |f|
  .container
    = render 'form', f: f
    .btn-group
      = button_tag(:update.ta, class: 'btn btn-primary')
      = link_to(:cancel.ta, params[:redirect] || {action: :show, controller: :games}, class: 'btn btn-default')

app/views/base/new.html.haml
.container
  = simple_form_for resource, class: 'form' do |f|
    - if params[:redirect]
      = hidden_field_tag(:redirect, params[:redirect])
    = render 'form', f: f
    .col-md-5
    .col-md-3
      .btn-group
        = button_tag(:create.ta, class: 'btn btn-primary')
        = link_to(:cancel.ta, params[:redirect] || {action: :index}, class: 'btn btn-default')

app/views/base/update.html.haml
edit.html.haml