config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :games, only: [:show] do
        member do
          post :prepare
          post :confirm
          post :evaluate
          get :historic
        end
      end
    end
  end

  namespace :backend do
    resources :games
    resources :game_turns
    resources :participants
    resources :scenarios
    resources :scenario_broadcasts
    resources :scenario_curves
    resources :scenario_issues
    resources :users
    resources :catalog_items
    root to: 'scenarios#index'
  end

  resources :games do
    collection do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
    end
    member do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
      get :current_turn_broadcasts_and_curves
      get :turns
      post :prepare
      post :start
      post :cancel
      post :pause
      post :resume
      post :stop
      post :trigger_issue
      post :pay_expenses
      post :evaluate
    end
  end
  resources :participants
  resources :participants do
    member do
      get :affairs_with, to: 'participants#affairs_with', path: 'affairs_with/:other_id'
    end
  end
  resources :farms
  resources :actors
  resources :loans
  resources :participations
  resources :contracts do
    member do
      get :execute
      post :execute
      post :cancel
    end
  end
  resources :deal_items, only: [:destroy], path: 'deal-items'
  resources :deals, except: [:index] do
    collection do
      post :add_to_cart
    end
    member do
      post :cancel
      post :checkout
      patch :change_quantity, path: 'change-quantity'
      patch :change_unit_pretax_amount, path: 'change-unit-pretax-amount'
    end
  end
  resources :users
  resources :insurances

  root to: 'games#index'
end

app/models/participant.rb
# = Informations
#
# == License
#
# Serious - Serious Game based on Ekylibre
# Copyright (C) 2015-2015 Ekylibre SAS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# == Table: participants
#
#  access_token      :string
#  application_url   :string
#  borrower          :boolean          default(FALSE), not null
#  closed            :boolean          default(FALSE), not null
#  code              :string           not null
#  contractor        :boolean          default(FALSE), not null
#  created_at        :datetime
#  customer          :boolean          default(FALSE), not null
#  game_id           :integer          not null
#  id                :integer          not null, primary key
#  insured           :boolean          default(FALSE), not null
#  insurer           :boolean          default(FALSE), not null
#  lender            :boolean          default(FALSE), not null
#  logo_content_type :string
#  logo_file_name    :string
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  name              :string           not null
#  nature            :string           not null
#  present           :boolean          default(FALSE), not null
#  stand_number      :string
#  subcontractor     :boolean          default(FALSE), not null
#  supplier          :boolean          default(FALSE), not null
#  tenant            :string
#  updated_at        :datetime
#  zone_height       :integer
#  zone_width        :integer
#  zone_x            :integer
#  zone_y            :integer
#

class Participant < ActiveRecord::Base
  extend Enumerize
  enumerize :nature, in: [:farm, :actor], predicates: true
  belongs_to :game
  has_many :catalog_items, inverse_of: :participant
  has_many :participations
  has_many :ratings, -> { order(:rated_at) }, class_name: 'ParticipantRating'
  has_many :users, through: :participations
  has_many :sales,      class_name: 'Deal', foreign_key: :supplier_id
  has_many :purchases,  class_name: 'Deal', foreign_key: :customer_id
  has_many :borrowings, class_name: 'Loan', foreign_key: :borrower_id
  has_many :lendings,   class_name: 'Loan', foreign_key: :lender_id
  has_many :subcontractings, class_name: 'Contract', foreign_key: :contractor_id
  has_many :contractings,    class_name: 'Contract', foreign_key: :subcontractor_id
  has_many :insurerings, class_name: 'Insurance', foreign_key: :insurer_id
  has_many :insuredings, class_name: 'Insurance', foreign_key: :insured_id

  has_attached_file :logo, styles: {
    identity: ['200x200#', :png]
  }

  # [VALIDATORS[ Do not edit these lines directly. Use `rake clean:validations`.
  validates_datetime :logo_updated_at, allow_blank: true, on_or_after: Time.new(1, 1, 1, 0, 0, 0, '+00:00')
  validates_numericality_of :logo_file_size, :zone_height, :zone_width, :zone_x, :zone_y, allow_nil: true, only_integer: true
  validates_inclusion_of :borrower, :closed, :contractor, :customer, :insured, :insurer, :lender, :present, :subcontractor, :supplier, in: [true, false]
  validates_presence_of :code, :game, :name, :nature
  # ]VALIDATORS]
  validates_uniqueness_of :name, scope: :game_id
  validates :tenant, uniqueness: true, if: :farm?
  validates_attachment_content_type :logo, content_type: /image/

  scope :actor, -> { where(nature: 'actor') }
  scope :farm,  -> { where(nature: 'farm') }

  accepts_nested_attributes_for :catalog_items, allow_destroy: true

  delegate :current_date, to: :game

  before_validation do
    if farm?
      self.borrower = true
      self.subcontractor = true
      self.customer = true
      self.insured = true
      self.tenant ||= code
      self.access_token ||= Devise.friendly_token
      if self.application_url.blank? && Serious::Slave.domain
        self.application_url = "#{Serious::Slave.protocol}://#{self.code}.#{Serious::Slave.domain_with_port}"
      end
    end
  end

  def products
    if application_url
      get('/products').map(&:symbolize_keys)
    elsif !catalog_items.nil?
      catalog_items.collect do |item|
        {
          name: item.variant_name,
          variant: item.variant,
          catalog_item_id: item.id
        }
      end
    else
      []
    end
  end

  validate do
    errors.add(:lender, :invalid) if lender if farm?
  end

  def unique_name
    "serious_#{id}"
  end

  def unique_id
    "s#{id.to_s(36)}"
  end

  def number
    I18n.transliterate(name.mb_chars.downcase).gsub(/[^a-zA-Z0-9]/, '').to_i(36)
  end

  def color
    val = number
    k = 10
    l = 16
    m = 2
    offset = 64
    r = 17
    g = 13
    b = 23
    c = ''
    c << ((val * r / m).modulo(k) * l + offset).to_s(16).rjust(2, '0')
    c << ((val * g / m).modulo(k) * l + offset).to_s(16).rjust(2, '0')
    c << ((val * b / m).modulo(k) * l + offset).to_s(16).rjust(2, '0')
    c
  end

  def abbreviation
    I18n.transliterate(name).gsub(/[^a-zA-Z0-9@\s]/, '').split(/\s+/).delete_if { |w| %w(de des du la le les au aux).include?(w) }[0..1].map { |w| w[0..0] }.join.upcase
  end

  def affairs_with(other)
    list = []
    list += sales.where(customer: other).to_a
    list += purchases.where(supplier: other).to_a
    list += borrowings.where(lender: other).to_a
    list += lendings.where(borrower: other).to_a
    list += subcontractings.where(subcontractor: other).to_a
    list += contractings.where(contractor: other).to_a
    list
  end

  def transfer_quality_rating
    contracts = self.contractings.where(state: [:cancelled, :executed])
    average = 2 * (contracts.sum(:quality_rating).to_f || 0.0) / contracts.count
    post("/guides/quality", {rating: average})
  end

  def domain
    application_url.gsub(/^https?:\/\//, '').gsub(/\:\d+$/, '')
  end

  # Perform a POST access on REST API of foreign app
  def post(path, params = {}, options = {})
    options[:content_type] ||= :json
    options[:Authorization] = "simple-token #{self.access_token}"
    RestClient.post(request_url(path), params.to_json, options)
  end

  # Perform a POST access on REST API of foreign app
  def patch(path, params = {}, options = {})
    options[:content_type] ||= :json
    options[:Authorization] = "simple-token #{self.access_token}"
    RestClient.patch(request_url(path), params.to_json, options)
  end

  # Perform a GET access on REST API of foreign app
  def get(path, params = {}, options = {})
    options[:accept] ||= :json
    options[:content_type] ||= :json
    options[:params] = params
    options[:Authorization] = "simple-token #{self.access_token}"
    JSON.parse RestClient.get(request_url(path), options)
  end

  def request_url(path = nil)
    "#{application_url}/seriously/v1#{path}"
  end
end

app/controllers/backend/participants_controller.rb
# == License
# Serious - Serious Game based on Ekylibre
# Copyright (C) 2015 Ekylibre SAS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

class Backend::ParticipantsController < Backend::BaseController
  manage_restfully
end

app/controllers/participants_controller.rb
class ParticipantsController < BaseController
  before_action :check_game

  def index
    if current_participation
      redirect_to controller: :games, action: :show, id: current_participation.game_id
    else
      redirect_to controller: :games, action: :index
    end
  end

  def show
    return unless find_resource
    render layout: false if params[:nolayout]
  end

  def affairs_with
    participant = Participant.find_by(id: params[:id])
    other = Participant.find_by(id: params[:other_id])
    if participant
      render json: participant.affairs_with(other).to_json
    else
      render json: 'nil'
    end
  end

  protected

  def find_resource
    @participant = Participant.find_by(id: params[:id])
    unless @participant
      redirect_to :index, alert: 'Participant not found'
      return false
    end
    true
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  # Show a participant card with logo and minimal infos
  def participant_card(participant, options = {}, &block)
    options[:content] = capture(participant, &block) if block_given?
    render 'participants/card', participant: participant, content: options.delete(:content), options: options
  end

  # Show a participant logo
  def participant_logo(participant)
    if participant.logo.file?
      image_tag(participant.logo.url(:identity))
    else
      content_tag(:div, participant.abbreviation, class: 'participant-abbreviation', style: "background-color: ##{participant.color}")
    end
  end

  def items_block(participant, reflection, options = {})
    collection = participant.send(reflection)
    if options[:relative_to] && options[:relative_to] != participant
      fail "Options :as is needed for #{reflection}" unless options[:as]
      collection = collection.where(options[:as] => options[:relative_to])
    end
    if collection.any?
      html = render 'participants/items_block', reflection: reflection, collection: collection, item_partial: "participants/item_#{reflection.to_s.singularize}"
      return html if options[:wrap].is_a? FalseClass
      if options[:wrap].is_a?(Hash)
        return content_tag(:div, html, options[:wrap])
      else
        return content_tag(:div, html, class: 'col-md-6')
      end
    end
  end
end

app/views/participants/_card.html.haml
.participant-card
  = link_to(participant_logo(participant), participant_path(participant), class: 'participant-logo')
  .participant-details
    - if participant.present
      .participant-stand-number= participant.stand_number
    .participant-title
      = options[:title] || participant.name
      - if current_user.administrator? && current_participation
        - if current_participation.organizer? || current_participation.participant == participant
          %small
            = link_to(edit_backend_participant_path(participant)) do
              %i.glyphicon.glyphicon-pencil
    - if content
      = content
    - elsif !content.is_a?(FalseClass)
      .participant-labels
        %span.label.label-primary= participant.class.model_name.human
        - [:contractor, :subcontractor, :supplier, :customer, :lender, :borrower].each do |state|
          - if participant.send(state)
            %span.label.label-success= Participant.human_attribute_name(state)
      - if false # participant.present
        .participant-info= "#{participant.name} est présent à l'événement, vous pouvez le retrouver à l'emplacement : #{participant.stand_number}"

      :ruby
        users = participant.participations.where.not(user_id: nil).order(:id).map do |participation|
          user = participation.user
          link_to(user.name, user_path(user.id))
        end
      .participant-members= h('Membres : ') + users.to_sentence.html_safe

app/views/participants/_form.html.haml
%h1 Participant
= field_set do
  .row
    .col-md-6= f.input :name
    .col-md-3= f.input :code
    .col-md-3= f.input :present
  .row
    .col-md-6= f.input :application_url
    .col-md-6= f.input :logo

  .row
    .col-md-3= f.input :stand_number
  .row
    .col-md-3= f.input :supplier
    .col-md-3= f.input :customer
    .col-md-3= f.input :lender
    .col-md-3= f.input :borrower

  .row
    .col-md-3= f.input :contractor
    .col-md-3= f.input :subcontractor
    .col-md-3= f.input :insurer
    .col-md-3= f.input :insured

app/views/participants/_graph.html.haml
.curve
  %h3 Trésorie
  :ruby
      serie = {name: @curve.name, data: @curve.steps.map{|s| [s.turn , s.amount.to_f]}}
      if @curve.interpolation_method_previous?
        serie[:step] = 'left'
      elsif @curve.interpolation_method_following?
        serie[:step] = 'right'
      end
  = line_chart([serie],chart: {height: 150}, y_axis: {title: {text: "#{:value.tl} (#{@curve.unit_name})"}})

app/views/participants/_item_borrowing.html.haml
.col-xs-2= item.number
.col-xs-4= link_to(item.lender_name, participant_path(item.lender, redirect: request.fullpath))
.col-xs-3.decimal= "#{item.interest_percentage}%/#{item.turns_count}M"
.col-xs-3.decimal= item.amount.l(currency: :EUR)

app/views/participants/_item_insurering.html.haml
.col-xs-2= item.id
.col-xs-4= link_to(item.insured.name, participant_path(item.insured, redirect: request.fullpath))
.col-xs-3.decimal= "#{item.unit_pretax_amount.l(currency: 'EUR')} payé/#{item.unit_refundable_amount.l(currency: 'EUR')} remboursable"
.col-xs-3.decimal= item.amount.l(currency: :EUR)

app/views/participants/_item_lending.html.haml
.col-xs-2= item.number
.col-xs-4= link_to(item.borrower_name, participant_path(item.borrower, redirect: request.fullpath))
.col-xs-3.decimal= "#{item.interest_percentage}%/#{item.turns_count}M"
.col-xs-3.decimal= item.amount.l(currency: :EUR)

app/views/participants/_item_purchase.html.haml
.col-xs-2= link_to(item.number, deal_path(item, redirect: request.fullpath))
.col-xs-4= link_to(item.supplier_name, participant_path(item.supplier, redirect: request.fullpath))
.col-xs-2
  %span.label.label-info= item.state.text
.col-xs-4.decimal= item.amount.l(currency: :EUR)

app/views/participants/_item_sale.html.haml
.col-xs-2= link_to(item.number, deal_path(item, redirect: request.fullpath))
.col-xs-4= link_to(item.customer_name, participant_path(item.customer, redirect: request.fullpath))
.col-xs-2
  %span.label.label-info= item.state.text
.col-xs-4.decimal= item.amount.l(currency: :EUR)

app/views/participants/_item_subcontracting.html.haml
.col-xs-2= item.id
.col-xs-4= link_to(item.contractor.name, participant_path(item.contractor, redirect: request.fullpath))
.col-xs-6= link_to(item.name, contract_path(item))

app/views/participants/_items_block.html.haml
.items-block
  %h3= "my_#{reflection}".tl
  .items-list
    - collection.each do |item|
      .items-item
        .row= render item_partial, item: item

app/views/participants/_purchase.html.haml
- deal = @participant.sales.where(customer_id: current_participant.id, state: :draft).first
.col-md-8
  .catalog
    %h3 Produits à acheter
    .items-list
      - @participant.products.each do |product|
        - unit_pretax_amount = current_game.scenario.value_of(product[:variant], current_turn)
        - next unless unit_pretax_amount
        .items-item
          .row
            .col-md-8.catalog-item-title{title: product[:name].to_s.humanize}= product[:name].to_s.humanize
            .col-md-2.decimal.catalog-item-price= unit_pretax_amount.l(currency: :EUR)+ ' HT'
            .col-md-2.catalog-item-quantity
              = link_to({controller: :deals, action: :add_to_cart, customer_id: current_participant.id,
                          supplier_id: @participant.id, unit_pretax_amount: unit_pretax_amount,
                          catalog_item_id: product[:catalog_item_id], product_id: product[:id],
                           variant: product[:variant], tax: product[:tax]}, method: :post) do
                %i.glyphicon.glyphicon-shopping-cart
.col-md-4
  #cart= render 'deals/cart', deal: deal, supplier: @participant

app/views/participants/_sell.html.haml
- deal = current_participant.sales.where(customer_id: @participant.id, state: :draft).first
.col-md-8
  .catalog
    %h3 Produits à vendre
    .items-list
      - current_participant.products.each do |product|
        - unit_pretax_amount = current_game.scenario.value_of(product[:variant], current_turn)
        - next unless unit_pretax_amount
        .items-item
          .row
            .col-md-8.catalog-item-title{title: product[:name].to_s.humanize}= product[:name].to_s.humanize
            .col-md-2.decimal.catalog-item-price= unit_pretax_amount.l(currency: :EUR)+ ' HT'
            .col-md-2.catalog-item-quantity
              = link_to({controller: :deals, action: :add_to_cart, customer_id: @participant.id,
                  supplier_id: current_participant.id,unit_pretax_amount: unit_pretax_amount,
                  catalog_item_id: product[:catalog_item_id], product_id: product[:id],variant: product[:variant],
                  tax: product[:tax]}, method: :post) do
                %i.glyphicon.glyphicon-shopping-cart

.col-md-4
  #cart= render 'deals/cart', deal: deal, supplier: current_participant

app/views/participants/show.html.haml
.container

  = participant_card(@participant)

  - if current_participant
    .row
      = tabbox(:participant) do |t|
        - if (@participant.present? && current_participant.farm?) || (current_participation && current_participation.organizer?)
          = t.tab :contact do
            .jumbotron
              %h1 Sur place uniquement
              %p Rendez-vous directement sur son stand pour faire affaire avec lui. Seul lui pourra effectuer les opérations (ventes, achats, emprunts...) que vous souhaitez.
        - else
          -# Deals
          - if @participant.products.any? && current_participant != @participant && current_turn
            = t.tab :purchase do
              = render "purchase"
          - if current_participant.products.any? && current_participant != @participant && current_turn
            = t.tab :sell do
              = render "sell"
          -# Insurance
          - if current_participant.insurer && @participant.insured && current_turn
            = t.tab :insure do
              .col-md-8
                .catalog
                  = link_to('Assurer la ferme',new_insurance_path(insurer_id: current_participant.id,
                            insured_id: @participant.id, redirect: request.fullpath), class: 'btn btn-default')
          - elsif current_participant.insured && @participant.insurer && current_turn
            = t.tab :insure_yourself do
              .col-md-8
                .catalog
                  = link_to("S'assurer", new_insurance_path(insurer_id: @participant.id,
                            insured_id: current_participant.id, redirect: request.fullpath), class: 'btn btn-default')
          -# Loans
          - if current_participant.lender && @participant.borrower && current_turn
            = t.tab :lend do
              .col-md-8
                .catalog
                  = link_to('Prêter', new_loan_path(lender_id: current_participant.id, borrower_id: @participant.id, redirect: request.fullpath),
                             class: 'btn btn-default')
          - elsif current_participant.borrower && @participant.lender && current_turn
            = t.tab :borrow do
              .col-md-8
                .catalog
                  = link_to('Emprunter', new_loan_path(lender_id: @participant.id, borrower_id: current_participant.id, redirect: request.fullpath), class: 'btn btn-default')

          -# Contracts
          - if current_participant.contractor && @participant.subcontractor && current_turn
            = t.tab :missionate do
              .col-md-8
                .catalog
                  = link_to('Missionner', new_contract_path(contractor_id: current_participant.id, subcontractor_id: @participant.id, redirect: request.fullpath),
                             class: 'btn btn-default')
          - elsif current_participant.subcontractor && @participant.contractor && current_turn
            = t.tab :operate do
              .col-md-8
                .catalog
                  = link_to('Traiter', new_contract_path(contractor_id: @participant.id, subcontractor_id: current_participant.id, redirect: request.fullpath), class: 'btn btn-default')

        = t.tab :transactions do
          = items_block(current_participant, :purchases, relative_to: @participant, as: :supplier)
          = items_block(current_participant, :sales,     relative_to: @participant, as: :customer)
          = items_block(current_participant, :contractings,    relative_to: @participant, as: :contractor)
          = items_block(current_participant, :subcontractings, relative_to: @participant, as: :subcontractor)
          = items_block(current_participant, :lendings,   relative_to: @participant, as: :borrower)
          = items_block(current_participant, :borrowings, relative_to: @participant, as: :lender)
          = items_block(current_participant, :insuredings, relative_to: @participant, as: :insurer)
          = items_block(current_participant, :insurerings, relative_to: @participant, as: :insured)