config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :games, only: [:show] do
        member do
          post :prepare
          post :confirm
          post :evaluate
          get :historic
        end
      end
    end
  end

  namespace :backend do
    resources :games
    resources :game_turns
    resources :participants
    resources :scenarios
    resources :scenario_broadcasts
    resources :scenario_curves
    resources :scenario_issues
    resources :users
    resources :catalog_items
    root to: 'scenarios#index'
  end

  resources :games do
    collection do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
    end
    member do
      get :current_turn, to: 'games#show_current_turn', path: 'current-turn'
      get :current_turn_broadcasts_and_curves
      get :turns
      post :prepare
      post :start
      post :cancel
      post :pause
      post :resume
      post :stop
      post :trigger_issue
      post :pay_expenses
      post :evaluate
    end
  end
  resources :participants
  resources :participants do
    member do
      get :affairs_with, to: 'participants#affairs_with', path: 'affairs_with/:other_id'
    end
  end
  resources :farms
  resources :actors
  resources :loans
  resources :participations
  resources :contracts do
    member do
      get :execute
      post :execute
      post :cancel
    end
  end
  resources :deal_items, only: [:destroy], path: 'deal-items'
  resources :deals, except: [:index] do
    collection do
      post :add_to_cart
    end
    member do
      post :cancel
      post :checkout
      patch :change_quantity, path: 'change-quantity'
      patch :change_unit_pretax_amount, path: 'change-unit-pretax-amount'
    end
  end
  resources :users
  resources :insurances

  root to: 'games#index'
end

app/models/deal.rb
# = Informations
#
# == License
#
# Serious - Serious Game based on Ekylibre
# Copyright (C) 2015-2015 Ekylibre SAS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# == Table: deals
#
#  amount        :decimal(19, 4)   default(0), not null
#  created_at    :datetime
#  customer_id   :integer          not null
#  game_id       :integer          not null
#  id            :integer          not null, primary key
#  invoiced_at   :datetime
#  pretax_amount :decimal(19, 4)   default(0), not null
#  state         :string           not null
#  supplier_id   :integer          not null
#  updated_at    :datetime
#

# A deal is a sale or a purchase between a customer and a supplier.
class Deal < ActiveRecord::Base
  extend Enumerize
  belongs_to :game
  belongs_to :customer, class_name: 'Participant'
  belongs_to :supplier, class_name: 'Participant'
  has_many :items, class_name: 'DealItem', dependent: :destroy
  enumerize :state, in: [:draft, :invoice, :cancelled], default: :draft, predicates: true

  # [VALIDATORS[ Do not edit these lines directly. Use `rake clean:validations`.
  validates_datetime :invoiced_at, allow_blank: true, on_or_after: Time.new(1, 1, 1, 0, 0, 0, '+00:00')
  validates_numericality_of :amount, :pretax_amount, allow_nil: true
  validates_presence_of :amount, :customer, :game, :pretax_amount, :state, :supplier
  # ]VALIDATORS]

  delegate :name, to: :supplier, prefix: true
  delegate :name, to: :customer, prefix: true

  accepts_nested_attributes_for :items

  alias_attribute :number, :id

  before_validation do
    update_totals
    self.state ||= 'draft'
  end

  # Sets totals in columns without saving
  def update_totals
    self.pretax_amount = items.sum(:pretax_amount)
    self.amount = items.sum(:amount)
  end

  # Update totals and save! it
  def update_totals!
    update_totals
    save!
  end

  # Confirm deal and transfer data to foreign apps
  def checkout
    items_list = items.collect do |item|
      item.attributes.symbolize_keys.slice(:product_id, :variant, :tax, :unit_pretax_amount, :unit_amount, :pretax_amount, :amount, :quantity).delete_if { |_k, v| v.blank? }
    end

    invoiced_on = customer.current_date

    # Send data to customer
    # For a customer, a deal is a purchase
    if customer.application_url?
      customer.post('/purchases', # invoiced_on: invoiced_on,
                    supplier: {
                      last_name: supplier.name,
                      code: supplier.code
                    },
                    items: items_list)
    end

    # Send data to supplier
    # For a supplier, a deal is a sale
    if supplier.application_url?
      supplier.post('/sales', # invoiced_on: invoiced_on,
                    customer: {
                      last_name: customer.name,
                      code: customer.code
                    },
                    items: items_list)
    end

    update_column(:state, :invoice)
  end

  # Cancel deal and transfer order to foreign apps
  def cancel
    fail NotImplementedError
  end
end

app/controllers/deals_controller.rb
class DealsController < BaseController
  before_action :check_running_game

  def show
    @deal = Deal.find(params[:id])
  end

  def new
    @deal = Deal.new(customer: @customer, supplier: @supplier)
  end

  def checkout
    deal = Deal.find(params[:id])
    deal.checkout
    redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier == current_participant ? deal.customer : deal.supplier)
  end

  def cancel
    # fail NotImplementedError
    deal = Deal.find(params[:id])
    if deal.draft?
      Deal.destroy deal
    else
      deal.cancel
    end
    redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier == current_participant ? deal.customer : deal.supplier)
  end

  def destroy
    deal = Deal.find(params[:id])
    Deal.destroy(deal)
    redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier == current_participant ? deal.customer : deal.supplier)
  end

  def add_to_cart
    supplier = Participant.find(params[:supplier_id])
    customer = Participant.find(params[:customer_id])
    # fail 'No way' unless supplier == current_participant || current_participant == customer
    # fail 'No way again' unless catalog_item.participant == supplier

    unless (deal = customer.purchases.where(supplier_id: supplier.id, state: :draft).order(id: :desc).first)
      deal = customer.purchases.create!(supplier: supplier, game: supplier.game)
    end

    if !(catalog_item_id = params[:catalog_item_id]).nil?
      item = deal.items.find_or_initialize_by(catalog_item_id: catalog_item_id)
    elsif !(product_id = params[:product_id]).nil?
      item = deal.items.find_or_initialize_by(product_id: product_id, variant: params[:variant], tax: params[:tax],
                                              unit_pretax_amount: params[:unit_pretax_amount])
    elsif !(variant = params[:variant]).nil?
      item = deal.items.find_or_initialize_by(variant: variant)
    else
      item = nil
      fail "Erreur l'item n'existe pas"
    end
    item.unit_pretax_amount = params[:unit_pretax_amount].to_d
    unless item.nil?
      item.quantity += params[:quantity] || 1
      item.save!
      redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier ==
                                                           current_participant ? deal.customer : deal.supplier)
    end
  end

  def change_quantity
    deal = Deal.find(params[:id])
    item = deal.items.find(params[:item_id])
    if params[:quantity].to_d >= 1
      item.quantity = params[:quantity]
      item.save!
    else
      DealItem.destroy(item)
    end
    deal.reload
    if request.xhr?
      render partial: 'cart', locals: { deal: deal, supplier: deal.supplier }
    else
      redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier ==
                                                           current_participant ? deal.customer : deal.supplier)
    end
  end

  def change_unit_pretax_amount
    deal = Deal.find(params[:id])
    item = deal.items.find(params[:item_id])
    if params[:unit_pretax_amount].to_d >= 1
      item.unit_pretax_amount = params[:unit_pretax_amount]
      item.save!
    else
      DealItem.destroy(item)
    end
    deal.reload
    if request.xhr?
      render partial: 'cart', locals: { deal: deal, supplier: deal.supplier }
    else
      redirect_to params[:redirect] || participant_url(current_participant.nil? ? deal.supplier : deal.supplier ==
                                                           current_participant ? deal.customer : deal.supplier)
    end
  end

end

app/views/deals/_cart.html.haml
- if deal and deal.items.any?
  .cart
    %h3= :cart.tl
    .cart-content
      = render 'deals/items', deal: deal
      = link_to('Valider la commande', {controller: :deals, id: deal.id, action: :checkout}, method: :post, class: 'btn btn-primary btn-block')
- else
  .help-block
    .help-content Cliquez sur les produits désirés pour les ajouter au panier.

= items_block(current_participant, :purchases, relative_to: supplier, as: :supplier, wrap: {})
= items_block(current_participant, :sales,     relative_to: supplier, as: :customer, wrap: {})

app/views/deals/_form.html.haml
.container
  = participant_card(@deal.supplier, title: "Boutique #{@deal.supplier.name}")

  .row
    .col-md-8
      .catalog
        %h3 Catalogue des produits
        .items-list
          - @deal.supplier.catalog_items.each do |catalog_item|
            .items-item
              .row
                .col-md-8.catalog-item-title{title: catalog_item.variant_name}= catalog_item.variant_name
                .col-md-2.decimal.catalog-item-price= catalog_item.amount.l(currency: :EUR)
                .col-md-2.catalog-item-quantity
                  - quantity = 0
                  - if (item = @deal.items.find_by(variant: catalog_item.variant))
                    - quantity = item.quantity
                  .btn-group
                    = link_to({controller: :deals, action: :increment, catalog_item_id: catalog_item.id}, method: :post, class: 'btn btn-xs btn-default') do
                      %i.glyphicon.glyphicon-plus
                    -# %span.btn.btn-default= quantity
                    = link_to({controller: :deals, action: :decrement, catalog_item_id: catalog_item.id}, method: :patch, class: 'btn btn-xs btn-default', disabled: quantity <= 0) do
                      %i.glyphicon.glyphicon-minus
    .col-md-4
      #cart= render 'cart', deal: @deal

app/views/deals/_items.html.haml
%table.table
  %thead
    %tr
      %th Article
      %th Quantité
      %th Montant
      %th
        %span.glyphicon.glyphicon-remove
  %tfoot
    %tr
      %th.deal-amount{colspan: 1}= 'Total HT'
      %th.deal-amount{colspan: 3}= deal.pretax_amount.l(currency: :EUR)
    %tr
      %th.deal-amount{colspan: 1}= 'Total TTC'
      %th.deal-amount{colspan: 3}= deal.amount.l(currency: :EUR)
  %tbody
    - deal.items.each do |item|
      %tr
        %td= item.variant_name
        %td.decimal-value
          = link_to(item.quantity, change_quantity_deal_path(deal.id, item_id: item.id), remote: true, method: :patch, data: {change_quantity: :new_quantity.tl} )
        %td.decimal-value
          = link_to(item.unit_pretax_amount.l(currency: :EUR), change_unit_pretax_amount_deal_path(deal.id, item_id: item.id), remote: true, method: :patch, data: {change_unit_pretax_amount: :new_unit_pretax_amount.tl})
        %td
          = link_to(deal_item_path(item), method: :delete) do
            %i.glyphicon.glyphicon-remove

app/views/deals/show.html.haml
.container
  .page
    .supplier
      .name= @deal.supplier.name
      %p.coordinates
        14 avenue de la gare
        %br
        47000 AGEN
        %br
        Tel: 05 53 12 34 56
    .customer
      .name= @deal.customer.name
      %p.coordinates
        27 rue de la mairie
        %br
        47000 AGEN

    %h1= "#{@deal.state.text} n°#{@deal.number}"

    .items= render "items", deal: @deal

    - if @deal.items.any?
      = link_to("Accepter le devis", checkout_deal_path(@deal), method: :post, class: "btn btn-default")
    - if @deal.draft?
      = link_to("Supprimer le devis", deal_path(@deal), method: :delete, class: "btn btn-danger")
    - elsif @deal.invoice?
      = link_to("Annuler la facture", cancel_deal_path(@deal), method: :post, class: "btn btn-danger")